repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-symlinks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix, "--ignore=A001,A002,B007,B008,B017,B020,B028,B904,C411,C419,E402,E711,E721,E722,E731,E501,F811,F821,F841,N,PT,UP008,UP036"]
      # Run the formatter
      - id: ruff-format
